name: Quality check

on:
  workflow_call:

jobs:
  Quality_Check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/initial_setup.yml

      # Линтинг TypeScript
      - name: Linting TypeScript
        run: npm run lint

        # Unit тесты
      - name: Unit testing
        run: echo 'npm run unit'

      # Визуальные тесты
      - name: Screenshot testing
        run: echo 'npm run snapshot'
