name: Release Beta

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  Quality_Check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: ./.github/workflows/quality-check.yml

  Release:
    needs: Quality_Check
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/cache-restore.yml

      - name: Building project
        run: npm run build

      - name: Beta Release
        if: github.ref == 'refs/heads/dev'
        run: npx semantic-release -p "@semantic-release/commit-analyzer,@semantic-release/release-notes-generator,@semantic-release/npm,@semantic-release/github"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
