name: Release Beta

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  Initial_setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3

      # Кэширование node_modules
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Установка Node.js
      - name: Setting up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm # Встроенное кэширование npm для ускорения

      # Установка зависимостей
      - name: Installing modules
        run: npm ci

  Linting_typescript:
    runs-on: ubuntu-latest
    needs: Initial_setup
    steps:
      - uses: actions/checkout@v3

      # Восстановление кэша node_modules
      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      # Линтинг TypeScript
      - name: Linting TypeScript
        run: npm run lint

  Unit_testing:
    runs-on: ubuntu-latest
    needs: Initial_setup
    steps:
      - uses: actions/checkout@v3

      # Восстановление кэша node_modules
      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      # Unit тесты
      - name: Unit testing
        run: echo 'npm run unit'

  Screenshot_testing:
    runs-on: ubuntu-latest
    needs: Initial_setup
    steps:
      - uses: actions/checkout@v3

      # Восстановление кэша node_modules
      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      # Визуальные тесты
      - name: Screenshot testing
        run: echo 'npm run snapshot'

      # Сохранение артефактов (текущие скриншоты)
    #   - name: Upload Current Screenshots
    #     # Загружаем артефакты, даже если тесты упали
    #     if: always()
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: current-screenshots
    #       path: .loki/current

  Release:
    needs: [Initial_setup, Linting_typescript, Unit_testing, Screenshot_testing]
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/cache-restore.yml

      - name: Building project
        run: npm run build

      - name: Beta Release
        if: github.ref == 'refs/heads/dev'
        run: npx semantic-release -p "@semantic-release/commit-analyzer,@semantic-release/release-notes-generator,@semantic-release/npm,@semantic-release/github"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
